In [85]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv(r"C:\Users\om sai compurer1\Desktop\cust satisfaction\cust_satisfaction.csv")

In [87]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0


In [88]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [89]:
Gender ={
    'Male':0, 'Female':1
}

In [90]:
df['Gender'] = df['Gender'].map(Gender)


In [91]:
df['Customer Type'].unique()

<StringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

In [92]:
Customer_Type ={
    'Loyal Customer':0, 'disloyal Customer':1
}

In [93]:
df['Customer Type']= df['Customer Type'].map(Customer_Type)

In [94]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,0,1,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,1,0,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,1,0,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,0,0,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,0,0,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,0,1,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,1,1,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0


In [95]:
df['Type of Travel'].unique()

<StringArray>
['Personal Travel', 'Business travel']
Length: 2, dtype: str

In [96]:
Type_of_Travel ={
    'Business travel':0, 'Personal Travel':1
}
df['Type of Travel']= df['Type of Travel'].map(Type_of_Travel)

In [97]:
df['Class'].unique()
Class ={
    'Business':0, 'Eco':1, 'Eco Plus':2
}
df['Class']= df['Class'].map(Class)
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,0,1,0,0,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,1,0,0,0,satisfied,26,1142,5,4,5,0,0.0
3,1,0,0,0,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,0,0,0,0,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,0,0,0,0,satisfied,49,2347,5,5,4,0,0.0
103901,0,1,0,0,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,1,1,0,1,neutral or dissatisfied,22,1000,1,1,1,0,0.0


In [98]:
df['satisfaction'].unique()

<StringArray>
['neutral or dissatisfied', 'satisfied']
Length: 2, dtype: str

In [99]:
satisfaction ={
    'neutral or dissatisfied':0, 'satisfied':1
}
df['satisfaction']= df['satisfaction'].map(satisfaction)
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,0,13,460,5,4,5,25,18.0
1,0,1,0,0,0,25,235,1,3,1,1,6.0
2,1,0,0,0,1,26,1142,5,4,5,0,0.0
3,1,0,0,0,0,25,562,2,3,2,11,9.0
4,0,0,0,0,1,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,0,23,192,2,4,2,3,0.0
103900,0,0,0,0,1,49,2347,5,5,4,0,0.0
103901,0,1,0,0,0,30,1995,4,4,4,7,14.0
103902,1,1,0,1,0,22,1000,1,1,1,0,0.0


In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  int64  
 1   Customer Type               103904 non-null  int64  
 2   Type of Travel              103904 non-null  int64  
 3   Class                       103904 non-null  int64  
 4   satisfaction                103904 non-null  int64  
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(11)
memory usage: 9.5 MB


In [101]:
x = df.drop('satisfaction', axis=1)
y = df['satisfaction']

In [102]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('satisfaction', axis=1), df['satisfaction'], test_size=0.2, random_state=42)

In [103]:
x_train

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
20921,1,0,1,1,59,1046,2,3,4,12,3.0
36897,1,1,0,0,40,752,1,4,1,19,29.0
8468,0,0,1,1,65,383,1,5,1,0,0.0
53490,1,0,1,1,70,2239,5,5,5,0,0.0
78687,1,1,0,1,25,1358,1,3,1,3,15.0
...,...,...,...,...,...,...,...,...,...,...,...
54886,0,1,0,1,39,637,3,2,3,1,0.0
76820,0,0,1,1,17,646,3,2,3,0,2.0
103694,0,0,0,1,46,1197,4,3,1,260,263.0
860,1,0,0,1,37,320,5,4,5,0,0.0


In [104]:
y_train

20921     0
36897     0
8468      0
53490     0
78687     0
         ..
54886     0
76820     0
103694    0
860       1
15795     0
Name: satisfaction, Length: 83123, dtype: int64

In [105]:
x_test  

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
80638,1,0,1,1,26,861,5,4,5,0,0.0
43398,0,0,0,0,22,393,3,3,3,0,16.0
32751,1,0,1,1,59,196,4,4,4,37,34.0
33571,1,0,1,1,32,1020,4,4,4,27,4.0
71287,0,1,0,0,35,1117,2,3,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8158,0,1,0,0,42,236,1,4,1,0,0.0
53718,0,0,1,1,14,558,5,5,5,0,0.0
33319,0,0,1,1,9,1005,5,2,5,1,0.0
99162,1,0,0,0,45,3234,4,4,3,0,19.0


In [106]:
y_test

80638    0
43398    0
32751    0
33571    0
71287    0
        ..
8158     0
53718    0
33319    0
99162    1
96811    1
Name: satisfaction, Length: 20781, dtype: int64

In [107]:
df.dropna()

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,0,1,2,0,13,460,5,4,5,25,18.0
1,0,1,0,0,0,25,235,1,3,1,1,6.0
2,1,0,0,0,1,26,1142,5,4,5,0,0.0
3,1,0,0,0,0,25,562,2,3,2,11,9.0
4,0,0,0,0,1,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,1,0,1,0,23,192,2,4,2,3,0.0
103900,0,0,0,0,1,49,2347,5,5,4,0,0.0
103901,0,1,0,0,0,30,1995,4,4,4,7,14.0
103902,1,1,0,1,0,22,1000,1,1,1,0,0.0


In [108]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [109]:
from sklearn.svm import SVC
sv = SVC()


In [110]:
x_train

,Gender,Customer Type,Type of Travel,Class,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
20921,1,0,1,1,59,1046,2,3,4,12,3.0
36897,1,1,0,0,40,752,1,4,1,19,29.0
8468,0,0,1,1,65,383,1,5,1,0,0.0
53490,1,0,1,1,70,2239,5,5,5,0,0.0
78687,1,1,0,1,25,1358,1,3,1,3,15.0
...,...,...,...,...,...,...,...,...,...,...,...
54886,0,1,0,1,39,637,3,2,3,1,0.0
76820,0,0,1,1,17,646,3,2,3,0,2.0
103694,0,0,0,1,46,1197,4,3,1,260,263.0
860,1,0,0,1,37,320,5,4,5,0,0.0


In [111]:
x_train.shape

(83123, 11)

In [112]:
y_train.shape

(83123,)

In [113]:
print(x_train.dtypes)

Gender                          int64
Customer Type                   int64
Type of Travel                  int64
Class                           int64
Age                             int64
Flight Distance                 int64
Inflight entertainment          int64
Baggage handling                int64
Cleanliness                     int64
Departure Delay in Minutes      int64
Arrival Delay in Minutes      float64
dtype: object


In [114]:
print(x_train.isnull().sum())

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      251
dtype: int64


In [115]:
x_train = x_train.fillna(x_train.mean())

In [116]:
x_train['Arrival Delay in Minutes'] = x_train['Arrival Delay in Minutes'].fillna(x_train['Arrival Delay in Minutes'].mean())

In [117]:
lr.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [118]:
print(x_train.isnull().sum())

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64


In [120]:
print(x_test.isnull().sum())

Gender                         0
Customer Type                  0
Type of Travel                 0
Class                          0
Age                            0
Flight Distance                0
Inflight entertainment         0
Baggage handling               0
Cleanliness                    0
Departure Delay in Minutes     0
Arrival Delay in Minutes      59
dtype: int64


In [122]:
x_test = x_test.fillna(x_test.mean())

In [123]:
lr.predict(x_test)

array([0.3226039 , 0.62751943, 0.21216606, ..., 0.19028965, 0.76368331,
       0.34747384], shape=(20781,))

In [124]:
lr.predict(x_train)

array([0.07994697, 0.14561407, 0.0161763 , ..., 0.32221064, 0.76934879,
       0.28777743], shape=(83123,))

In [127]:
sv.fit(x_train, y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",False
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [128]:
sv.predict(x_test)

array([0, 0, 0, ..., 0, 1, 0], shape=(20781,))

In [129]:
sv.predict(x_train)

array([0, 0, 0, ..., 0, 0, 0], shape=(83123,))

In [131]:
import imblearn
from imblearn.over_sampling import SMOTE

In [132]:
from sklearn.tree import DecisionTreeRegressor

In [133]:
dtc = DecisionTreeRegressor()
dtc.fit(x_train,y_train)
pred = dtc.predict(x_test)
pred

array([0., 0., 0., ..., 1., 1., 1.], shape=(20781,))

In [134]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [135]:
import joblib
joblib.dump(dtc, 'cust_satisfaction_model.lb')


['cust_satisfaction_model.lb']

In [136]:
cust_satisfaction_model = joblib.load('cust_satisfaction_model.lb')


In [137]:
cust_satisfaction_model

,"criterion criterion: {""squared_error"", ""friedman_mse"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in the half mean Poisson deviance to find splits... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 0.24 Poisson deviance criterion.",'squared_error'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.For an example of how ``max_depth`` influences the model, see:ref:`sphx_glr_auto_examples_tree_plot_tree_regression.py`.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",None
,"max

In [138]:
cust_satisfaction_model.predict(x_test)

array([0., 0., 0., ..., 1., 1., 1.], shape=(20781,))

In [139]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
x ,y = load_iris(return_X_y=True)
from sklearn.naive_bayes import GaussianNB, MultinomialNB
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=7)
Mnb =MultinomialNB()
Mnb.fit(x_train, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [140]:
Mnb.score(x_test, y_test)

0.8333333333333334

In [141]:
from sklearn.cluster import KMeans
km =KMeans()
km.fit(x_train, y_train)


,"n_clusters n_clusters: int, default=8The number of clusters to form as well as the number ofcentroids to generate.For an example of how to choose an optimal value for `n_clusters` refer to:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_silhouette_analysis.py`.",8
,"init init: {'k-means++', 'random'}, callable or array-like of shape (n_clusters, n_features), default='k-means++'Method for initialization:* 'k-means++' : selects initial cluster centroids using sampling based on an empirical probability distribution of the points' contribution to the overall inertia. This technique speeds up convergence. The algorithm implemented is ""greedy k-means++"". It differs from the vanilla k-means++ by making several trials at each sampling step and choosing the best centroid among them.* 'random': choose `n_clusters` observations (rows) at random from data for the initial centroids.* If an array is passed, it should be of shape (n_clusters, n_features) and gives the initial centers.* If a callable is passed, it should take arguments X, n_clusters and a random state and return an initialization.For an example of how to use the different `init` strategies, see:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_digits.py`.For an evaluation of the impact of initialization, see the example:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_stability_low_dim_dense.py`.",'k-means++'
,"n_init n_init: 'auto' or int, default='auto'Number of times the k-means algorithm is run with different centroidseeds. The final results is the best output of `n_init` consecutive runsin terms of inertia. Several runs are recommended for sparsehigh-dimensional problems (see :ref:`kmeans_sparse_high_dim`).When `n_init='auto'`, the number of runs depends on the value of init:10 if using `init='random'` or `init` is a callable;1 if using `init='k-means++'` or `init` is an array-like... versionadded:: 1.2 Added 'auto' option for `n_init`... versionchanged:: 1.4 Default value for `n_init` changed to `'auto'`.",'auto'
,"max_iter max_iter: int, default=300Maximum number of iterations of the k-means algorithm for asingle run.",300
,"tol tol: float, default=1e-4Relative tolerance with regards to Frobenius norm of the differencein the cluster centers of two consecutive iterations to declareconvergence.",0.0001
,"verbose verbose: int, default=0Verbosity mode.",0
,"random_state random_state: int, RandomState instance or None, default=NoneDetermines random number generation for centroid initialization. Usean int to make the randomness deterministic.See :term:`Glossary `.",None
,"copy_x copy_x: bool, default=TrueWhen pre-computing distances it is more numerically accurate to centerthe data first. If copy_x is True (default), then the original data isnot modified. If False, the original data is modified, and put backbefore the function returns, but small numerical differences may beintroduced by subtracting and then adding the data mean. Note that ifthe original data is not C-contiguous, a copy will be made even ifcopy_x is False. If the original data is sparse, but not in CSR format,a copy will be made even if copy_x is False.",True
,"algorithm algorithm: {""lloyd"", ""elkan""}, default=""lloyd""K-means algorithm to use. The classical EM-style algorithm is `""lloyd""`.The `""elkan""` variation can be more efficient on some datasets withwell-defined clusters, by using the triangle inequality. However it'smore memory intensive due to the allocation of an extra array of shape`(n_samples, n_clusters)`... versionchanged:: 0.18 Added Elkan algorithm.. versionchanged:: 1.1 Renamed ""full"" to ""lloyd"", and deprecated ""auto"" and ""full"". Changed ""auto"" to use ""lloyd"" instead of ""elkan"".",'lloyd'


In [142]:
km.score(x_test, y_test)

-9.296924697199538

In [145]:
df.to_csv('cust_satisfaction_model_cleaned.csv', index=False)